language: scala
sudo: false
addons:
  apt:
    packages:
    - numactl
    - libnuma1
    - libnuma-dev
    - libnuma-dbg
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt
  - $HOME/ssl
  - $HOME/mongodb-linux-x86_64-2.6.12
  - $HOME/mongodb-linux-x86_64-amazon-3.2.10
scala: 2.11.8
jdk: oraclejdk8
env:
  - AKKA_VERSION=2.4.8 ITERATEES_VERSION=2.3.10
  - AKKA_VERSION=2.4.8 ITERATEES_VERSION=2.6.1
  - AKKA_VERSION=2.4.16 ITERATEES_VERSION=2.3.10
  - AKKA_VERSION=2.4.16 ITERATEES_VERSION=2.6.1
before_install: ./.ci_scripts/beforeInstall.sh $TRAVIS_SCALA_VERSION
script: ./.ci_scripts/validate.sh
after_success: ./.ci_scripts/afterSuccess.sh