language: scala
script: sbt ++$TRAVIS_SCALA_VERSION testOnly
scala:
  - "2.11.7"
  - "2.10.5"
jdk:
  - oraclejdk8
  - openjdk7
before_install:
- sudo ./.travis_scripts/beforeInstall.sh $TRAVIS_SCALA_VERSION